chore: adding e2e sections in cy configs that don't have them
cypress-io/cypress-example-recipes pull request #780
Opened 2022-06-10 22:20 UTC by elylucas

This PR adds e2e config sections to projects that did not have them. This was causing the ci pipelines to break in Cy 10.1.0 as it now requires there be a e2e or component section when in run mode.

This PR also changes some of the examples to run with retries the the Cypress config instead of using the test-retries scripts. It was unclear on what the script was trying to achieve, and the tests were flaky, so I felt using the built in retries mechanism makes sense.

2022-06-10 22:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress-example-recipes?pullRequest=780) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress-example-recipes?pullRequest=780) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress-example-recipes?pullRequest=780) it.</sub>

2022-06-13 14:40 UTC, jaffrepaul commented on examples/blogs__assertion-counting/cypress.config.js
> +  e2e: { },
```suggestion
  e2e: {},
```

2022-06-13 14:42 UTC, jaffrepaul commented on examples/stubbing-spying__intercept/cypress.config.js
> +    openMode: 1,
Just curious why the value for openMode as well here and not other projects?

2022-06-13 14:43 UTC, jaffrepaul requested changes
Added a couple tiny tweaks and a clarifying q 👍

2022-06-13 15:08 UTC, elylucas commented on examples/stubbing-spying__intercept/cypress.config.js
> +    openMode: 1,
```suggestion
    openMode: 0,
```

2022-06-13 15:13 UTC, jaffrepaul reviewed
So just to clarify, our recommendation around this issue to include a testing type object in the config, even if it's empty? Curious why that creates issues without it.

2022-06-13 15:15 UTC, jaffrepaul commented on examples/stubbing-spying__intercept/cypress.config.js
> +    openMode: 0,
It looks like the default is already "0" https://docs.cypress.io/guides/guides/test-retries#Global-Configuration

2022-06-14 14:00 UTC, merged